version: '3.8'

services:
  bot:
    image: botimage
    container_name: bot
    restart: "unless-stopped"
    command: python -O src
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8083:8083"

  postgres:

    image: postgres:latest

    container_name: db
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: mj_user
      POSTGRES_PASSWORD: sJcVHAT9
      POSTGRES_DB: mj_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:

    image: redis:latest
    container_name: redis

    restart: "on-failure"
    volumes:
      - ./redis:/data
    command: redis-server --stop-writes-on-bgsave-error no
